### ISSUE TITLE
[Bug] Failed to launch in udev

### ISSUE THREAD

**Issue by Halfarne** [Ottatop/pinnacle#44] opened 2023-08-05 13:44 UTC
I can't launch compositor in udev. It returns that i have no permission. This is only compositor that does that. I can normally launch other compositors like MagmaWM.
I am running Nixos.

**Comment by Ottatop** [comment] 2023-08-05 14:36
Can you provide launch output?

The only thing I can think of is that Pinnacle opens a Unix socket at `/tmp`. I know very little about NixOS, but is it possible that the permissions are insufficient? If you can successfully launch the winit backend, though, that's probably not the issue.

**Comment by Ottatop** [comment] 2023-08-05 21:34
Ok I spun up a NixOS VM and can see the `permission denied` error at `drm_atomic`. Just need to figure out why that's happening.

**Comment by Ottatop** [comment] 2023-08-06 02:31
If you have time, can you pull `main`, run udev with the included [shell.nix](https://github.com/Ottatop/pinnacle/blob/main/shell.nix), and see if you can get any further into the compositor? I managed to get into udev on a live usb, but it had some *big* graphical glitches.

**Comment by Halfarne** [comment] 2023-08-06 09:14
So, i tried to run it in winit and again i had no permission. I tried adding myself to the render group if it might help, it did nothing.
Here are the logs from running it from udev and winit:
[winit.log](https://github.com/Ottatop/pinnacle/files/12269048/winit.log)
[udev.log](https://github.com/Ottatop/pinnacle/files/12269049/udev.log)

When i tried to run with winit as root it worked, but with udev as root it showed a black screen and the crashed.

**Comment by Ottatop** [comment] 2023-08-06 15:04
Can you run winit with
```sh
PINNACLE_CONFIG="./api/lua/example_config.lua" RUST_BACKTRACE=full RUST_LOG=trace cargo run -- --winit &> winit_verbose.log
```
and udev with
```sh
PINNACLE_CONFIG="./api/lua/example_config.lua" RUST_BACKTRACE=full RUST_LOG=trace cargo run -- --udev &> udev_verbose.log
```
and give me `winit_verbose.log` and `udev_verbose.log`?

My guess is that there is some difference in file/dir permissions between your system and mine. You shouldn't need to be root to get it to work.

**Comment by Halfarne** [comment] 2023-08-06 16:50
Here are the logs:
[udev_verbose.log](https://github.com/Ottatop/pinnacle/files/12270035/udev_verbose.log)
[winit_verbose.log](https://github.com/Ottatop/pinnacle/files/12270036/winit_verbose.log)

**Comment by Ottatop** [comment] 2023-08-06 17:44
Strange, is Cargo not giving you backtraces? All these logs seem to just print what error was returned and end abruptly, and I'm trying to get backtraces to see what line causes the issue.

**Comment by Halfarne** [comment] 2023-08-06 18:00
And i am running it from flake instead of shell.
I copied the flake from cosmic-comp, it somehow couldn't compile with cargo and dev shell.
[flake.nix](https://github.com/Ottatop/pinnacle/files/12270146/flake.nix.txt)

**Comment by Halfarne** [comment] 2023-08-06 18:16
> And i am running it from flake instead of shell. I copied the flake from cosmic-comp, it somehow couldn't compile with cargo and dev shell. [flake.nix](https://github.com/Ottatop/pinnacle/files/12270146/flake.nix.txt)

Now i tried to run it again from nix shell and it compiled and it gave me back same errors:
[udev_verbose.log](https://github.com/Ottatop/pinnacle/files/12270175/udev_verbose.log)
[winit_verbose.log](https://github.com/Ottatop/pinnacle/files/12270176/winit_verbose.log)

**Comment by Ottatop** [comment] 2023-08-06 19:42
Judging from the error, it seems to be something in `io::Error` with kind `PermissionDenied`. Looking at the code, the only thing I can see is the problem are [these lines](https://github.com/Ottatop/pinnacle/blob/bbb711f1a90c7ccbc5a5a0058fe47434aa763a3b/src/api.rs#L88-L105).

You said that running as root made it work. Can you tell me what permissions your `/tmp` directory has? If the problem is that your user doesn't have sufficient privileges to write to `/tmp`, then it would make sense that using root causes it to succeed.

**Comment by Ottatop** [comment] 2023-08-07 00:52
Ok I've pushed some improvements to error handling. If you pull `main` and run as you've done previously, *assuming* my theory is correct, you should see some new error messages concerning a socket.

**Comment by Halfarne** [comment] 2023-08-07 15:39
Here are the logs:
[udev_verbose.log](https://github.com/Ottatop/pinnacle/files/12282109/udev_verbose.log)
[winit_verbose.log](https://github.com/Ottatop/pinnacle/files/12282111/winit_verbose.log)
In the `/tmp` directory i have full permissions.

**Comment by Ottatop** [comment] 2023-08-07 16:58
If you have full permissions, then I guess there's something weird with your `/tmp` directory because the logs show errors that Pinnacle can't remove the socket at `/tmp/pinnacle_socket` due to not having permission to do so.

I've pushed more changes to `main`. See if you can run Pinnacle as before, but this time also pass in the `SOCKET_DIR` environment variable set to a directory that you *know* you have write permissions to. Maybe try `SOCKET_DIR="./"`? This should open the socket in the root of the git project.

**Comment by Halfarne** [comment] 2023-08-07 17:37
I looked again into the `/tmp` and the `pinnacle_socket` was owned by root. I deleted it and now i can launch winit without problems, but the udev has still some errors:
[udev_verbose.log](https://github.com/Ottatop/pinnacle/files/12283523/udev_verbose.log)
but this time it behaving like, when i was running it with root, it started, but then it crashed.

**Comment by Ottatop** [comment] 2023-08-07 17:41
I think udev will crash if it doesn't find a config, which is something I need to fix. Were you running with `PINNACLE_CONFIG="./api/lua/example_config.lua"`?

**Comment by Halfarne** [comment] 2023-08-07 17:44
Yes:
`PINNACLE_CONFIG="./api/lua/example_config.lua" RUST_BACKTRACE=full RUST_LOG=trace cargo run -- --udev`
and error is: `thread 'main' panicked at 'Stream doesn't exist', src/backend/udev.rs:904:22`

**Comment by Ottatop** [comment] 2023-08-07 17:49
Ok, then this is probably an ordering bug where the event loop processes udev events before it processes socket events.

Check in on #46 while I work on a fix.

**Comment by Ottatop** [comment] 2023-08-07 18:01
Can you switch to `udev_fix` and see if the problem is fixed? I can't seem to reproduce your issue on Arch, so you'll have to be my guinea pig :smile:

**Comment by Halfarne** [comment] 2023-08-07 18:28
After switching it works, but when i launch it it does not respond, i can move the mouse, but that is all i can do, the keyboard does not responding. I can't even switch tty, so i have to turn of pc.

**Comment by Ottatop** [comment] 2023-08-07 18:35
Oops, sorry about that. I haven't added tty switching yet.

For future debugging,  `Ctrl + Shift + Alt + Escape` is hardcoded to kill the compositor.

Can you redirect the output to a log file and give it to me? It seems that the config process is immediately crashing. Just run and then kill the compositor.

**Comment by Halfarne** [comment] 2023-08-07 18:49
Here is the log: [udev_verbose.log](https://github.com/Ottatop/pinnacle/files/12284246/udev_verbose.log)
I had to remove the `RUST_LOG=trace`, because the file was too big to upload here.

**Comment by Ottatop** [comment] 2023-08-07 18:54
Ok it says it couldn't find `~/.config/pinnacle/init.lua`. Did you have PINNACLE_CONFIG set?

Alternatively you can just copy [`example_config.lua`](https://github.com/Ottatop/pinnacle/blob/main/api/lua/example_config.lua) to `~/.config/pinnacle/init.lua`.

**Comment by Halfarne** [comment] 2023-08-07 19:03
I have the config in `~/.config/pinnacle/init.lua`  and i tried it with `PINNACLE_CONFIG=~/.config/pinnacle/init.lua`

**Comment by Ottatop** [comment] 2023-08-07 19:06
In that case, can you try to quit the compositor with `Ctrl + Alt + Q` instead of `Ctrl + Shift + Alt + Escape`? If `Ctrl + Alt + Q` works, then that means the config is active and working.

**Comment by Halfarne** [comment] 2023-08-07 19:08
No, it doesn't do anything.

**Comment by Ottatop** [comment] 2023-08-07 19:14
It seems that Rust isn't expanding the `~` to your home directory, which I need to change. Can you try with the full path to the config instead?

**Comment by Halfarne** [comment] 2023-08-07 19:20
It still don't work, but i noticed that the led on the keyboard for caps lock and num lock didn't changed when i pushed the buttons, so maybe the system don't get, that the lock buttons were pushed.

**Comment by Ottatop** [comment] 2023-08-07 19:26
I notice the same thing with the lock buttons. It's probably another thing I have to fix.

Ok, can you give me:
- The full command you used to run Cargo, and
- Another udev log with redirected output (it can just be at log level `DEBUG`)

It's *really* weird that Pinnacle can't seem to find your config file. Can you also run the same command but using the winit backend and see if `Ctrl + Alt + Q` closes the winit window? If winit can successfully find the file but udev can't, that's even weirder because they delegate to the same function.

**Comment by Halfarne** [comment] 2023-08-07 19:33
The commands are: 
`PINNACLE_CONFIG="/home/halfarne/.config/pinnacle/init.lua" RUST_BACKTRACE=full RUST_LOG=debug cargo run -- --udev`
`PINNACLE_CONFIG="/home/halfarne/.config/pinnacle/init.lua" RUST_BACKTRACE=full RUST_LOG=debug cargo run -- --winit`

The log files: [udev_verbose.log](https://github.com/Ottatop/pinnacle/files/12284626/udev_verbose.log), [winit_verbose.log](https://github.com/Ottatop/pinnacle/files/12284627/winit_verbose.log).

**Comment by Ottatop** [comment] 2023-08-07 19:46
Can you check if you have `lua5_4` installed and not an older version?

**Comment by Halfarne** [comment] 2023-08-07 19:58
I changed the lua package and it still don't work.

**Comment by Ottatop** [comment] 2023-08-07 20:02
Can you send me logs?

Redirect with `&>` instead of just `>`. This will also send `stderr` and output from Lua into the log so I can understand the issue.

**Comment by Halfarne** [comment] 2023-08-08 14:26
I tried to look into the config, if there wasn't something i had changed, and when i changed the key that were supposed to change the workspace back to the original (i originally changed them to q, w. e. r, t) it worked.

**Comment by Ottatop** [comment] 2023-08-08 14:33
Great! Guess I can close this issue now.

Just curious, what did you put in for the keys before? If you can give me just those lines, maybe I can see what went wrong.

**Comment by Halfarne** [comment] 2023-08-08 14:36
This:
```

    input.keybind({ mod_key }, keys.KEY_q, function()
        tag.switch_to("1")
    end)
    input.keybind({ mod_key }, keys.KEY_w, function()
        tag.switch_to("2")
    end)
    input.keybind({ mod_key }, keys.KEY_e, function()
        tag.switch_to("3")
    end)
    input.keybind({ mod_key }, keys.KEY_r, function()
        tag.switch_to("4")
    end)
    input.keybind({ mod_key }, keys.KEY_t, function()
        tag.switch_to("5")
```

**Comment by Halfarne** [comment] 2023-08-08 14:38
> This:
> 
> ```
> 
>     input.keybind({ mod_key }, keys.KEY_q, function()
>         tag.switch_to("1")
>     end)
>     input.keybind({ mod_key }, keys.KEY_w, function()
>         tag.switch_to("2")
>     end)
>     input.keybind({ mod_key }, keys.KEY_e, function()
>         tag.switch_to("3")
>     end)
>     input.keybind({ mod_key }, keys.KEY_r, function()
>         tag.switch_to("4")
>     end)
>     input.keybind({ mod_key }, keys.KEY_t, function()
>         tag.switch_to("5")
> ```

When i am looking at this now, i see that i probably should be `keys.q` instead of `keys.KEY_q`

**Closed** 2023-08-08 14:39 UTC
Labels: bug

**Comment by Ottatop** [comment] 2023-08-08 14:41
Yep, that would be the problem.

Are you using [Lua Language Server](https://github.com/LuaLS/lua-language-server)? There are instructions on the README to set it up to have [api/lua](https://github.com/Ottatop/pinnacle/tree/main/api/lua) as a library.
This should provide autocomplete and documentatation, as well as *some* error checking.

Anyway, thank you for helping me out!
